import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import React from 'react';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import { ReduxProvider } from '@/store/providers';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-inter'
});
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
         <ReduxProvider>
        <Providers>
          {children}
          <Toaster
            position='top-center'
            toastOptions={{
              duration: 3000,
              style: { fontSize: '14px', fontWeight: 500 }
            }}
          />
        </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
