import React from 'react';

import { Geist, Geist_Mono, Inter } from 'next/font/google';

import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';

import { ReduxProvider } from '@/store/providers';

import { Providers } from './providers';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-inter'
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang={'en'}>
    <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}>
      <ReduxProvider>
        <Providers>
          {children}
          <Toaster
            position={'top-center'}
            toastOptions={{
              duration: 3000,
              style: { fontSize: '14px', fontWeight: 500 }
            }}
          />
        </Providers>
      </ReduxProvider>
    </body>
  </html>
);

export default RootLayout;
